### ISSUE TITLE
syntax error & more code request

### ISSUE THREAD

**Issue by suradaBANG** [RuiWang1998/ShapleyExplanationNetworks#1]
Hi, I'm trying to using ShapNet to visualize a CNN classifier.

- I noticed a similar syntax error in README doc like:
`inputs = torch.randn(32, dim, ), ) `

- And how can I have this visualization image occurred in your paper:
![](https://cdn.jsdelivr.net/gh/suradaBANG/imagehub@master/img/image-20210308112439212.png)

- By the way, is that ok to share your EXPERIMENTS & VISUALIZATIONS code (the 3rd part of your 2021 ICLR paper)?

Anyway, thanks a lot for the project!
Wish you all the best!

**Comment by RuiWang1998** [comment]
Hi,

1. Thanks for pointing out the error! We'll fix that soon!

2. To generate the figure, all you need to do is to train a `DeepConvShapNet` as shown in the code with different regularizations! For the first row you need none of it. For the second row, you need to perform l-1 regularization on the explanations at the end of the forward pass (before the summation that brings out the outputs), and, for the third row, on the explanations on every layer. For plotting, we just mask out pixel values close to zero.

3. Yes it is definitely in the work! We have been a bit busy but the experimental code will be released soon!

**Comment by suradaBANG** [comment]
Thank you for your work!
