### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by oppsitre** [RuiWang1998/ShapleyExplanationNetworks#2]
Hi,
   I try to run the code in the box "For a Shapley Module“，but I only got the following error

   C:\Users\hp\anaconda3\envs\py38\lib\site-packages\torch\tensor.py:904: UserWarning: Named tensors 
   and all their associated APIs are an experimental feature and subject to change. Please do not use them 
  for anything important until they are released as stable. (Triggered internally at  . 
  .\c10/core/TensorImpl.h:930.)
  return super(Tensor, self).rename(names).

     Do you know the reason of it? How I can avoid it?
     Thank you!

**Comment by RuiWang1998** [comment]
It's a warning from PyTorch. We used an experimental feature called Named Tensor. It just says that they are not stable yet. It's a warning, not an error.
